# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch(“RAILS_MAX_THREADS”) { 5 } %>
  # you need to put your username and password here
  # username: cathybergmann
  # password: <%=ENV["123"]%>
development:
  <<: *default
  # Your app name(e.g. my app directory folder name is fotoset-backend)
  database: cathybergmann_development
production:
  <<: *default
  # Your app name(e.g. my app directory folder name is fotoset-backend)
  # you don’t need username and password here below
  database: cathybergmann_production
  username: cathybergmann
  password: <%= ENV['CATHY_BERGMANN_PASSWORD'] %>